#!/usr/bin/env bash

path=$(dirname "$(readlink -f "$0")")

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root!"
    exit 1
fi

cat > /etc/systemd/system/sms-server.service << EOF
[Unit]
Description=SMS Server
After=multi-user.target

[Service]
Type=simple
Restart=always
User=$(whoami)
ExecStart=/usr/bin/python $(pwd)/${path}/main.py

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable sms-server.service
systemctl start sms-server.service
