#!/usr/bin/env bash

path=$(dirname "$(readlink -f "$0")")

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root!"
    exit 1
fi

cp "${path}/sms-server.service" /etc/systemd/system
systemctl daemon-reload
systemctl enable sms-server.service
systemctl start sms-server.service
