#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root!"
    exit 1
fi

systemctl stop sms-server.service
systemctl disable sms-server.service
rm /etc/systemd/system/sms-server.service
systemctl daemon-reload
